name: CI

on: [push, pull_request]

jobs:
  build-macos-ubuntu:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
      - name: Build
        run: for file in $(find . -name "*.sln"); do dotnet build $file; done
      - name: Run tests
        run: for file in $(find . -name "*.sln"); do dotnet test $file; done
